server:
  port: 8083
spring:
  datasource:
    username: root
    password: HJC916924
    url: jdbc:mysql://39.106.82.217:3306/our_web?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      maxActive: 20
      maxWait: 60000
  redis:
    host: 39.106.82.217
    port: 6379
    password: HJC916924
#    lettuce:
#      pool:
#        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 100 # 连接池中的最大空闲连接
#        min-idle: 50 # 连接池中的最小空闲连接
#        max-wait: 6000ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    timeout: 1000ms
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
  servlet:
    multipart:
      max-file-size: 100000000
      max-request-size: 200000000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.paperfly.mapper: debug

sms:
  config:
    accessKeyId: LTAI4GF6h4nEioGZLZWNEVhd
    secret: lWBPj8BsvaqicG4ScjiOas1Yy25vYf
    signName: PaperFly
    templateCode: SMS_190791537
